{{- if .Values.s3.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "noaa-daemon.fullname" . }}-s3
  labels:
    {{- include "noaa-daemon.labels" . | nindent 4 }}
type: Opaque
data:
  access-key-id: {{ .Values.s3.accessKeyId | b64enc | quote }}
  secret-access-key: {{ .Values.s3.secretAccessKey | b64enc | quote }}
{{- end }}
