{{- if .Values.litestream.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "noaa-oracle.fullname" . }}-s3
  labels:
    {{- include "noaa-oracle.labels" . | nindent 4 }}
type: Opaque
data:
  access-key-id: {{ .Values.litestream.s3AccessKeyId | b64enc | quote }}
  secret-access-key: {{ .Values.litestream.s3SecretAccessKey | b64enc | quote }}
{{- end }}
