{{- if or .Values.secrets.privateKey.create .Values.secrets.privateKey.generate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "noaa-oracle.fullname" . }}-keys
  labels:
    {{- include "noaa-oracle.labels" . | nindent 4 }}
type: Opaque
stringData:
  oracle.pem: {{ .Values.secrets.privateKey.value | quote }}
{{- end }}
