{{- if or .Values.secrets.privateKey.create .Values.secrets.privateKey.generate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "noaa-oracle.fullname" . }}-keys
  labels:
    {{- include "noaa-oracle.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.privateKey.generate }}
  {{/* Generate a random 32-byte key in PEM format for local dev/testing */}}
  oracle.pem: |
    -----BEGIN EC PRIVATE KEY-----
    {{ randBytes 32 | b64enc }}
    -----END EC PRIVATE KEY-----
  {{- else }}
  oracle.pem: {{ .Values.secrets.privateKey.value | quote }}
  {{- end }}
{{- end }}
