{{- if .Values.secrets.privateKey.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "noaa-oracle.fullname" . }}-keys
  labels:
    {{- include "noaa-oracle.labels" . | nindent 4 }}
type: Opaque
data:
  oracle.pem: {{ .Values.secrets.privateKey.value | b64enc | quote }}
{{- end }}
