apiVersion: v1
kind: Service
metadata:
  name: {{ include "noaa-oracle.fullname" . }}
  labels:
    {{- include "noaa-oracle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if and .Values.litestream.enabled .Values.litestream.httpServer.enabled }}
    - port: {{ .Values.litestream.httpServer.port }}
      targetPort: litestream-http
      protocol: TCP
      name: litestream
      {{- if .Values.litestream.httpServer.nodePort }}
      nodePort: {{ .Values.litestream.httpServer.nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "noaa-oracle.selectorLabels" . | nindent 4 }}
