apiVersion: v2
name: noaa-daemon
description: NOAA weather data fetching daemon
type: application
version: 0.1.0
appVersion: "1.9.2"

home: https://github.com/tee8z/noaa-oracle
sources:
  - https://github.com/tee8z/noaa-oracle

maintainers:
  - name: tee8z
    email: tee8z@protonmail.com

keywords:
  - noaa
  - weather
  - daemon
  - data-fetcher
